pixelsdb/pixels

- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsPlugin.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/block/EncoderUtil.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/block/VarcharArrayBlock.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/block/VarcharArrayBlockEncoding.java
1. fix unkonwn block encoding factory.
2. fix array out-of-bound in VarcharArrayBlockEncoding.readBlock().
> [Issue #49] fix bugs in VarcharArrayBlock

- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/Decoder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/Encoder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/RunLenByteDecoder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/RunLenIntDecoder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BinaryColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BooleanColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ByteColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/CharColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntegerColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/VarcharColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/BinaryColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/ByteColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/ColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DoubleColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/LongColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/StructColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimestampColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/VectorizedRowBatch.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
Release resources in PixelsRecordReaderImpl when its close method is called.
> [Issue #58]: add close method to resources.

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/MemoryMappedFile.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheReader.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestMemFile.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheManager.java
The read / write coordination according to rw_flag and read_count has been implemented.
> [Issue #67] implement cache read / write coordination.

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheReader.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsRadix.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/ChunkId.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/ChunkSeq.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
Details are shown in the comments marked as Issue #67 (patch).
> [Issue #67]: Implement cache read lease and optimize read performance.

- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsConnector.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsMetadata.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsPageSource.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsPageSourceProvider.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsSplit.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsSplitManager.java
This is only implemented in Presto.
To be implemented in hive.
> [Issue #78]: avoid cache probing on uncached tables in Presto.

- pixels-hive/src/main/java/io/pixelsdb/pixels/hive/mapred/PixelsInputFormat.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsConnector.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsMetadata.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsPageSource.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsPageSourceProvider.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsSplit.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsSplitManager.java
> [Issue #78]: avoid cache probing on uncached tables in Hive.

- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
> [Issue #85]: fix list table error when schema is empty.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
- pixels-listener/src/main/java/io/pixelsdb/pixels/listener/PixelsEventListener.java
And move it into pixels-listener.
> [Issue #87]: remove explicit gc from PixelsReader.

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheReader.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
> [Issue #88]: fix MAX_READER_COUNT.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DateColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimeColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/DateColumnStats.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/DateStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/TimeColumnStats.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/TimestampColumnStats.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/DatetimeUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/DateColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimeColumnWriter.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbColumnDao.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbLayoutDao.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbSchemaDao.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbTableDao.java
- pixels-load/src/test/java/io/pixelsdb/pixels/load/TestSplitString.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/block/TimeArrayBlock.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/block/TimeArrayBlockEncoding.java
Fix the following two bugs:
1. the return value of some insert and update methods in metadata are not correct.
2. getLayout throughs Exception if no layout exists.
> [Issue #98]: fix insert/update related metadata service and getLayout.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BitUtils.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestBitUtils.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestDynamicIntArray.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
We fixed the null value support in pixels-core, and optimized the decoding performance for isnull array.
> [Issue #99]: fix null value storage.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/DateColumnStats.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/DateStatsRecorder.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
Use long for min/max of Date type.
> [Issue #145]: fix date type for Presto-0.215.

- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
Take empty schema as a normal case.
> [Issue #156]: fix empty schema.

- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/block/VarcharArrayBlock.java
Previously, VarcharArrayBlock.retainedBytesForEachPart returns a much larger value than the correct retained size of the block.
> [Issue #167]: fix retained size calculation for VarcharArrayBlock.

- README.md
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheConfig.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/EtcdUtil.java
- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/test/java/io/pixelsdb/pixels/core/compactor/TestPixelsCompactor.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/Daemon.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheManager.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Config.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/ConsumerGenerator.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/single/Loader.java
- pixels-load/src/test/java/io/pixelsdb/pixels/load/TestPixelsWriter.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/impl/PixelsMetadataProxy.java
- pixels-presto/src/test/java/io/pixelsdb/pixels/presto/split/TestISplitSplitsIndex.java
- pixels-tools/src/main/java/io/pixelsdb/pixels/test/CacheGetPerf.java
- pixels-tools/src/main/java/io/pixelsdb/pixels/test/CacheIndexPerf.java
- pixels-tools/src/main/java/io/pixelsdb/pixels/test/CacheReadPerf.java
- pixels-tools/src/main/java/io/pixelsdb/pixels/test/CacheReadStat.java
- pixels-tools/src/main/java/io/pixelsdb/pixels/test/CheckCacheContent.java
- pixels-tools/src/test/java/io/pixelsdb/pixels/test/CacheReaderPerfMulti.java
- pixels-tools/src/test/java/io/pixelsdb/pixels/test/UpdateCacheLayout.java
- pixels-tools/src/test/java/io/pixelsdb/pixels/test/WorkloadAnalyzer.java
- scripts/sbin/stop-pixels.sh
1. Remove signal handlers, use shutdown hook to handle shut down of Pixels daemons, use kill -15 to shutdown daemons gracefully.
2. Fix the state check and heartbeat of Pixels daemons.
3. Remove shutdown hook in EtcdUtil.
4. Fix some names, comments, and docs.
> [Issue #181]: fix start and stop of pixels-daemon.

- README.md
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheConfig.java
- pixels-common/pom.xml
- pixels-daemon/pom.xml
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheManager.java
- pixels-load/pom.xml
- pixels-presto/pom.xml
1. Do not create the states and files for the columnar cache if the cache is disabled.
2. Fix the docs and poms.
> [Issue #186]: skip cache initialization if cache is disabled.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/S3.java
Use sync client to do copy and delete.
> [Issue #190]: fix data copying between S3 buckets.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Scheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/SortMergeScheduler.java
- pixels-common/src/main/resources/pixels.properties
Fix the issue and refine the names of some members in MergedRequest.
> [Issue #205]: fix integer overflow in request merging.

- README.md
- pixels-hive/pom.xml
- scripts/sbin/pin-cache.sh
- scripts/sbin/reset-cache.sh
- scripts/sbin/start-pixels.sh
- scripts/sbin/stop-pixels.sh
- scripts/sbin/unpin-cache.sh
- maven: remove pentaho ref:https://github.com/apache/hudi/pull/3034
- scripts: replace /home/ubuntu with $HOME to make it more general
- readme: Make the notice of HDFS more visible
> [Issue #210]: some minor improvements.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/DecimalColumnWriter.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsPageSource.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsRecordCursor.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/impl/PixelsTupleDomainPredicate.java
- pixels-presto/src/test/java/io/pixelsdb/pixels/presto/impl/TestPixelsPredicate.java
Change the type of column statistics of decimal from double to long.
> [Issue #208]: fix column statistics for decimal.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Storage.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalS3Reader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/HDFS.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/LocalFS.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/S3.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/TestS3.java
Support storing tables in S3 folders.
Remove id creation and check from S3 storage, only create and check id in getFileId() and delete id in delete().
> [Issue #189]: support folders on S3.

- pom.xml
> HOTFIX: revert dedentabot.

- README.md
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/StorageFactory.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
It is tested that Hadoop is currently optional. Thus we only update the docs to indicate that Hadoop is not necessary. some comments are also fixed.
> [Issue #231]: update docs and comments.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/exception/StorageException.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/S3.java
> [Issue #249]: remove InvalidActivityException.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/MinIO.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/TestMinIO.java
- pixels-core/pom.xml
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/lambda/Lambda.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/lambda/ScanInput.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/lambda/ScanInvoker.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/lambda/ScanOutput.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/predicate/ColumnFilter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/predicate/Filter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/lambda/TestInput.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/predicate/TestPredicate.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
- pom.xml
Fixed the bugs in ColumnFilter (Decimal was processed incorrectly, only null is not considered);
Add LambdaInvoker, add split size into ScanInput, and add the number of row groups into ScanOutput;
Handle the tail file and check the output visibility in ScanWorker;
Add validity check into PixelsRecordReader.
> [Issue #170]: support lambda scan.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Storage.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/AbstractS3.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/LocalFS.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/predicate/Bound.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
Previously, only file deletion worked.
> [Issue #170]: fix S3 folder deletion.

- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/LambdaJoinExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinType.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/Joiner.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/JoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/PartitionedJoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/SingleStageJoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/ChainJoinInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/JoinInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/PartitionedJoinInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/BroadcastJoinInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/ChainJoinInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/PartitionedJoinInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/plan/Join.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/plan/JoinEndian.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/plan/JoinGraph.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/plan/JoinedTable.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/plan/Table.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/TestLambdaJoinExecutor.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestBroadcastJoinInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestChainJoinInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestPartitionedJoinInvoker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedJoinWorker.java
By supporting join endian, we can put the small table on either left or right side of each join.
> [Issue #170]: support join endian.

- pixels-common/src/main/resources/pixels.properties
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/LambdaJoinExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinAdvisor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/SingleStageJoinOperator.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/WorkerCommon.java
- pixels-optimizer/pom.xml
1. implement join-advisor.
2. fix file schema read in workers.
3. refine join inputs and outputs, and existence check.
4. fix join endian of the first join in broadcast chain join.
> [Issue #258]: add join advisor and fix join execution.

- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/LambdaJoinExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/PartitionedJoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/BroadcastTableInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/JoinInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/BroadcastChainJoinInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/BroadcastJoinInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/PartitionedChainJoinInput.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestBroadcastChainJoinInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestBroadcastJoinInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestPartitionInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestPartitionedChainJoinInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestPartitionedJoinInvoker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/WorkerCommon.java
A set of broadcast joins on the left and a partitioned join on the right can be merged into a partitioned chain join.
> [Issue #258]: implement partitioned chain join.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/Integer128ColumnStats.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/Integer128StatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/Decimal.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/EncodingUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/Integer128.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/LongDecimal.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/LongDecimalColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimestampColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/ColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/LongDecimalColumnWriter.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/predicate/ColumnFilter.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/PixelsConsumer.java
- proto/metadata.proto
- proto/pixels.proto
Long decimal is currently not supported for column filtering.
Fix several bugs in column vector and type description.
> [Issue #203]: support long decimal with 38 max digit precision and scale.

- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
Avoid accessing partialAggregationInfo if it is not present.
> [Issue #170]: fix null-pointer in scan worker.

- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/AggregationWorker.java
Fix the bug: miss one after every 8 partial aggregation files.
> [Issue #170]: fix aggregation worker.

- pixels-load/src/main/java/io/pixelsdb/pixels/load/Main.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/PixelsConsumer.java
Make sure that the path of the source files ends with "/". Thus avoid reading other folders with the same prefix.
> [Issue #170]: fix loading path.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/CostBasedSplitsIndex.java
- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinAdvisor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/BroadcastTableInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/PartitionedTableInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/ScanTableInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/TableInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/plan/Table.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestBroadcastChainJoinInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestBroadcastJoinInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestPartitionedChainJoinInvoker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/AggregationWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/WorkerCommon.java
1. optimize file existence checking in lambda workers.
2. add partition row number limit.
3. add split row number limit.
4. fix pixels compactor.
> [Issue #170]: join optimization for very large datasets.

- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/DateColumnStats.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/DateStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DateColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DecimalColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DoubleColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/LongColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimeColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimestampColumnVector.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinAdvisor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/JoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/Operator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/PartitionedJoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/SingleStageJoinOperator.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedJoinWorker.java
1. optimize the hash function to reduce skew.
2. wait for the large side in a join and make the completion ratio configurable.
> [Issue #170]: optimizing hash functions.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/VectorizedRowBatch.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/PartitionInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/scan/Scanner.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionWorker.java
In hash partitioned join, push down projection into partition workers.
> [Issue #170]: implement partition projection.

- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinAdvisor.java
1. does not multiple the table input size by selectivity.
2. does not apply input splits adjustment for broadcast join if it is not read by every worker of the parent.
> [Issue #170]: improve join algorithm selection and broadcast split size adjustment.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-lambda/pom.xml
Also refined the pom of pixels-lambda.
> [Issue #170]: using multi-thread for column encoding in Pixels writer.

- scripts/spot/launch-script.sh
- scripts/spot/termination-handler.sh
Update the scripts that handle the reclaim and scaling of spot VMs.
> [Issue #170]: update spot scripts.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransContext.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/GcMonitor.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/utils/TestGcMonitor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinAdvisor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/operator/AggregationOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/operator/PartitionedJoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/operator/SingleStageJoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/output/Output.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/WorkerCommon.java
These will be used by the dynamic serverless switch.
> [Issue #170]: add trans concurrency and GC monitor, and tune log level.

- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/AggregationWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedJoinWorker.java
Remove existence check to reduce S3 request cost. This does not affect performance.
> [Issue #170]: remove existence check from workers.

- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/StarlingExecutor.java
1. the startling executor is for the experimental evaluation.
2. for the multi-pipeline broadcast join, previously, internal parallelism in applied to the output of the right child if the child is also a broadcast join. This is incorrect.
> [Issue #170]: add startling executor and fix the inputs of multi-pipeline broadcast join.

- pixels-common/pom.xml
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/PhysicalReaderUtil.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/PhysicalWriterUtil.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Storage.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/StorageFactory.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalRedisReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalRedisWriter.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/RedisOutputStream.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/Minio.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/Redis.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/TestRedis.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/StarlingExecutor.java
- pixels-lambda/pom.xml
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/AggregationWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/WorkerCommon.java
- pom.xml
Limitations: Currently, we only support single thread and standalone mode of Redis.
> [Issue #170]: support Redis storage.

- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/StarlingExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/aggregation/Aggregator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/PartialAggregationInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/AggregationInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/operator/AggregationOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/operator/StarlingAggregationOperator.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/aggregation/TestAggregator.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/AggregationWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
After adding partitioning, preaggregation is removed.
> [Issue #170]: add partitioning to aggregation and implement starling aggregation.

- pixels-common/pom.xml
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/MockReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/Mock.java
- pom.xml
Grpc and protobuf are upgraded to the versions used in google cloud client.
> [Issue #357]: fix compilation and dependency problem.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/LocalFS.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbViewDao.java
- proto/metadata.proto
LocalFS is also updated to check invalid paths.
> [Issue #371]: update metadata for view creation in Trino.

- NOTICE
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/direct/DirectIoLib.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalLocalReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/SortMergeScheduler.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BooleanColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DateColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntegerColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimeColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DictionaryColumnVector.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/TestByteBuf.java
Prevent the dictionary column vector from spanning multiple column chunks and fix byte buffer positioning in the other column vectors.
> [Issue #374]: fix the column vectors.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/PhysicalReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/AbstractS3Reader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalLocalReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/DirectRandomAccessFile.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/MappedRandomAccessFile.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/PixelsRandomAccessFile.java
- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReader.java
This is implemented using a thread pool. Hooking libaio or io_uring is much more complex; thus, leave it as a future work.
> [Issue #403] support async read on local fs.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/metrics/ReadPerfHistogram.java
- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/PixelsCoreConfig.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metrics/MetricsServer.java
- pixels-daemon/src/test/java/io/pixelsdb/pixels/daemon/metrics/TestJsonParse.java
- pixels-daemon/src/test/java/io/pixelsdb/pixels/daemon/metrics/TestMetricServer.java
- pixels-daemon/src/test/java/io/pixelsdb/pixels/daemon/metrics/TestPrometheus.java
Remove:
```
pixels.warehouse.path
```
Rename: 
```
metric.bytesms.interval --> metrics.bytesms.interval
metric.reader.json.dir --> metrics.reader.json.dir
metric.node.text.dir --> metrics.node.text.dir
metric.reader.collect.prob --> metrics.reader.collect.prob
pixels.gc.threshold --> experimental.gc.threshold
```
> [Issue #405] refine configuration properties.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntegerColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/IntegerColumnWriter.java
the data in integer and long column reader is 4/8 bytes aligned
> [Issue #417] the data in integer and long column reader is aligned

- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/StatExecutor.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
- proto/metadata.proto
- proto/turbo.proto
Automatically update row count of each table in the STAT command of pixels-cli.
> [Issue #459] update row count automatically.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/exception/QueryScheduleException.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/exception/QueryServerException.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/ExecutionHint.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/request/EstimateCostRequest.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/request/SubmitQueryRequest.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/response/GetResultResponse.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/ExecutorType.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/QueryQueues.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/QueryScheduleService.java
- pixels-common/src/main/resources/pixels.properties
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransContextManager.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransServiceImpl.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/turbo/QueryQueues.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/turbo/QueryScheduleQueues.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/turbo/QueryScheduleServer.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/turbo/QueryScheduleServiceImpl.java
- pixels-server/pom.xml
- pixels-server/src/main/java/io/pixelsdb/pixels/server/constant/RestUrlPath.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/MetadataController.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryController.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
- pixels-server/src/test/java/io/pixelsdb/pixels/server/TestMetadataAPI.java
- pixels-server/src/test/java/io/pixelsdb/pixels/server/TestQueryAPI.java
- proto/turbo.proto
Currently, cost estimation and cost collection are not implemented; hence we can not get the monetary cost of queries.
> [Issue #431] finish pixels query server.

- README.md
- docs/INSTALL.md
- pixels-common/src/main/resources/pixels.properties
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/StarlingPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/domain/StorageInfo.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/domain/StorageInfoBuilder.java
- pixels-storage/pixels-storage-redis/src/main/java/io/pixelsdb/pixels/storage/redis/Redis.java
- pixels-storage/pixels-storage-s3/src/main/java/io/pixelsdb/pixels/storage/s3/Minio.java
- pixels-storage/pixels-storage-s3/src/test/java/io/pixelsdb/pixels/storage/s3/TestMinio.java
- pixels-turbo/README.md
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestAggregationLambdaInvoker.java
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestBroadcastChainJoinLambdaInvoker.java
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestBroadcastJoinLambdaInvoker.java
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestPartialAggregationLambdaInvoker.java
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestPartitionLambdaInvoker.java
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestPartitionedChainJoinLambdaInvoker.java
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestPartitionedJoinLambdaInvoker.java
- pixels-turbo/pixels-invoker-vhive/src/test/java/io/pixelsdb/pixels/invoker/vhive/Main.java
- pixels-turbo/pixels-invoker-vhive/src/test/java/io/pixelsdb/pixels/invoker/vhive/TestAggregationVhiveInvoker.java
- pixels-turbo/pixels-invoker-vhive/src/test/java/io/pixelsdb/pixels/invoker/vhive/TestBroadcastChainJoinVhiveInvoker.java
- pixels-turbo/pixels-invoker-vhive/src/test/java/io/pixelsdb/pixels/invoker/vhive/TestBroadcastJoinVhiveInvoker.java
- pixels-turbo/pixels-invoker-vhive/src/test/java/io/pixelsdb/pixels/invoker/vhive/TestPartitionVhiveInvoker.java
- pixels-turbo/pixels-invoker-vhive/src/test/java/io/pixelsdb/pixels/invoker/vhive/TestPartitionedChainJoinVhiveInvoker.java
- pixels-turbo/pixels-invoker-vhive/src/test/java/io/pixelsdb/pixels/invoker/vhive/TestPartitionedJoinVhiveInvoker.java
- pixels-turbo/pixels-invoker-vhive/src/test/java/io/pixelsdb/pixels/invoker/vhive/TestScanVhiveInvoker.java
- pixels-turbo/pixels-scaling-ec2/src/main/scripts/launch-script.sh
- pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/WorkerCommon.java
- pixels-turbo/pixels-worker-vhive/src/test/java/TestConverter.java
> [Issue #466] fix storage endpoint config.

- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/StarlingPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/JoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/PartitionedJoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/SingleStageJoinOperator.java
We mark whether a broadcast chain join is complete when it is constructed. And we do not continue to add more broadcast joins into a complete broadcast chain join.
> [Issue #482] fix incorrect join plan for broadcast join after complete broadcast chain join.

- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
> [Issue #484] fix post partition for right side broadcast chain join.

- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/StarlingPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/domain/MultiOutputInfo.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/domain/OutputInfo.java
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestAggregationLambdaInvoker.java
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestPartialAggregationLambdaInvoker.java
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestPartitionLambdaInvoker.java
- pixels-turbo/pixels-invoker-vhive/src/test/java/io/pixelsdb/pixels/invoker/vhive/Utils.java
- pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BaseAggregationWorker.java
- pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BaseScanWorker.java
- pixels-turbo/pixels-worker-vhive/src/test/java/TestConverter.java
> [Issue #435] remove request id from scan output path.

- install.sh
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/PixelsConsumer.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-turbo/pixels-invoker-vhive/src/main/java/io/pixelsdb/pixels/invoker/vhive/VhiveInvoker.java
Using `mvn install` instead of `mvn package` in install.sh.
Fix exception print in vHive invoker.
> [Issue #391] minor changes.

- docs/INSTALL.md
- pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/ExecutionHint.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/QueryStatus.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/request/EstimateQueryCostRequest.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/request/GetQueryResultRequest.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/request/GetQueryStatusRequest.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/response/EstimateQueryCostResponse.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/response/GetQueryResultResponse.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/response/GetQueryStatusResponse.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/QueryScheduleService.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/turbo/QueryScheduleQueues.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/turbo/QueryScheduleServiceImpl.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryController.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
- pixels-server/src/test/java/io/pixelsdb/pixels/server/TestQueryAPI.java
- proto/turbo.proto
- scripts/sql/metadata_schema.sql
Also:
1. revise metadata_schema.sql and docs;
2. fix bugs related to auto-scaling in QueryScheduleService;
3. support query status check in a batch manner.
> [Issue #490] support relaxed and best-effort query execution.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
> [Issue #519] fix wrong column chunk offsets in a multi-row-group file

- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- proto/pixels.proto
> [Issue #524] using full path as the key in file footer cache

- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- proto/pixels.proto
> [Issue #522] add layout configurations into the file format

- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/InvertedSplitsIndex.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/SplitPattern.java
- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
Also fix an argument checking bug in PixelsCompactor. Closes #521.
> [Issue #521] support chunk aligned compact file

- pixels-cache/Makefile
- pixels-cache/pom.xml
- pixels-cli/pom.xml
- pixels-common/pom.xml
- pixels-core/pom.xml
- pixels-daemon/pom.xml
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
- pixels-example/pom.xml
- pixels-executor/pom.xml
- pixels-parser/pom.xml
- pixels-planner/pom.xml
- pixels-server/pom.xml
- pixels-storage/pixels-storage-gcs/pom.xml
- pixels-storage/pixels-storage-hdfs/pom.xml
- pixels-storage/pixels-storage-localfs/pom.xml
- pixels-storage/pixels-storage-mock/pom.xml
- pixels-storage/pixels-storage-redis/pom.xml
- pixels-storage/pixels-storage-s3/pom.xml
- pixels-turbo/pixels-invoker-lambda/pom.xml
- pixels-turbo/pixels-invoker-vhive/pom.xml
- pixels-turbo/pixels-scaling-ec2/pom.xml
- pixels-turbo/pixels-worker-common/pom.xml
- pixels-turbo/pixels-worker-lambda/pom.xml
- pixels-turbo/pixels-worker-vhive/pom.xml
- pom.xml
> [Issue #535] upgrade project to 0.2.0-SNAPSHOT

- .gitmodules
- cpp/.gitignore
- cpp/Makefile
- cpp/README.md
- cpp/pixels-reader/.gitignore
1. Rename duckdb to pixels-duckdb
2. Fix minor format
3. Change third_party to third-party
> [Issue #542] minor fix for pixels reader c++

- cpp/Makefile
- cpp/PixelsScanFunction.cpp
- cpp/README.md
- cpp/pixels-cxx.properties
1. config core number in pixels-cxx.properties
2. separate make pull and make
> Pixels cxx minor format v2

- docs/TPC-H.md
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/Main.java
Set the correct default value for the encoding level.
> [Issue #538] fix load command and docs

- docs/TPC-H.md
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/Main.java
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/QueryExecutor.java
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/StatExecutor.java
- pixels-cli/src/test/java/io/pixelsdb/pixels/cli/TestExecuteQuery.java
Now, the STAT and QUERY commands check layout selection from pixels.properties.
> [Issue #593] revise the parameters for the STAT and QUERY commands in pixels-cli.

- docs/INSTALL.md
- pixels-cache/README.md
- pixels-common/src/main/resources/pixels.properties
The documents of pixels-cache are now consistent with the implementation.
> [Issue #588] update the docs for pixels-cache

- pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/VectorColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/VectorColumnStats.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/VectorStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/ColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/VectorColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/ColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/VectorColumnWriter.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestVectorColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestVectorColumnWriter.java
- pixels-example/src/main/java/io/pixelsdb/pixels/example/core/ITTestReadVectorColumnFromS3.java
- pixels-example/src/main/java/io/pixelsdb/pixels/example/core/ITTestWriteVectorColumnToS3.java
- proto/pixels.proto
This PR implements a vector column type, with proper support in pixels writer, pixels reader and type description. This PR implements the functionality of writing vector column to s3 and then read from s3. The PR is now ready for review.
> [Issue #580] add vector column and its writer reader and related metadata handling

- docs/INSTALL.md
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/JvmUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/VectorColumnVector.java
The previous implementation is not compatible with JDK8.
> [Issue #580] ensure compatibility with JDK8

- docs/INSTALL.md
- pixels-turbo/README.md
Clean the main INSTALL.md and revise the README.md of pixels-turbo.
> [docs] revise docs for pixels-turbo

- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/PixelsConsumer.java
Previously, the number of rows in each row group was aligned to the default row batch size 1024.
> [Issue #616] ensure number of rows in each row group is strictly controlled by the LOAD command

- scripts/bin/jvm.config
- scripts/bin/run-class.sh
- scripts/sbin/datanodes
- scripts/sbin/start-coordinator.sh
- scripts/sbin/start-datanode.sh
- scripts/sbin/stop-coordinator.sh
- scripts/sbin/stop-datanode.sh
- Add config file `jvm.options` in `pixels/scripts/bin`
- Add config file `datanodes` in `pixels/scripts/sbin`. The format of each line is `hostname pixels_home[optional]`. Users can configure the hostname and Pixels home of all nodes and then start datanodes at once.
> [Issue #605] enhance the scripts

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsPhysicalReader.java
fix an error in updateLocalCache where the number of RowGroups in a file is smaller than in others.
> [Issue #624] fix an error in updateLocalCache

- cpp/CMakeLists.txt
- cpp/pixels-core/include/encoding/RunLenIntEncoder.h
- cpp/pixels-core/include/utils/EncodingUtils.h
- cpp/pixels-core/lib/encoding/RunLenIntEncoder.cpp
- cpp/pixels-core/lib/utils/EncodingUtils.cpp
- cpp/tests/unit_tests.cpp
C++ version of pixels encoder based on Java version
> [Issue #553] Implemented pixels encoding in C++

- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/Main.java
The EOF in a file may cause No new line exception when reading commands from the file.
> [Issue #631] fix reading commands from file

- cpp/PixelsScanFunction.cpp
- cpp/include/PixelsReadGlobalState.hpp
- cpp/include/PixelsReadLocalState.hpp
- cpp/pixels-common/CMakeLists.txt
- cpp/pixels-common/include/physical/BufferPool.h
- cpp/pixels-common/include/physical/StorageArrayScheduler.h
- cpp/pixels-common/include/utils/ColumnSizeCSVReader.h
- cpp/pixels-common/lib/physical/BufferPool.cpp
- cpp/pixels-common/lib/physical/StorageArrayScheduler.cpp
- cpp/pixels-common/lib/utils/ColumnSizeCSVReader.cpp
- cpp/pixels-core/lib/reader/PixelsRecordReaderImpl.cpp
- cpp/pixels-core/lib/reader/StringColumnReader.cpp
- cpp/pixels-core/lib/vector/VectorizedRowBatch.cpp
- cpp/pixels-cxx.properties
We need to add the following enhancement and fix the bug for Pixels C++:
1. add ssd array schedule for pixels
2. fix the issue that the file count of a dataset is smaller than the number of SSDs
3. fix the string column reader to read e1 and e2 encoding correctly
> Pixels C++ Enhancement and Fix bug

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
- pixels-cli/pom.xml
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/CompactExecutor.java
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/CopyExecutor.java
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/FileMetaExecutor.java
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/ImportExecutor.java
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/LoadExecutor.java
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/QueryExecutor.java
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/StatExecutor.java
- pixels-cli/src/test/java/io/pixelsdb/pixels/cli/TestExecuteQuery.java
- pixels-cli/src/test/java/io/pixelsdb/pixels/cli/TestPrintProtobuf.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/domain/OriginProjectionPattern.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Status.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderStreamImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsVersion.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterStreamImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
> [Issue #684] support print file metadata

- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
Use new Properties for each submit to avoid reuse of session.token.
> [Issue #691] fix trace token overwritten by subsequent query

- scripts/bin/run-class.sh
> [Issue #710] fix seperate jvm configurations for pixels coordinator and worker

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheWorker.java
> [Issue #713] fix unable to cache layout version 0

- pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/heartbeat/HeartbeatCoordinator.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/heartbeat/HeartbeatWorker.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/RdbPathDao.java
The metadata server failed to get file ids by uri.
> [Issue #715] fix get file id bug

- install.sh
modify the install.sh
the pixels-cxx.properties should also be copied
> [Issue #726] update install.sh to copy cpp properties

- pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/exception/EtcdException.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/lock/EtcdAutoIncrement.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/lock/EtcdMutex.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/lock/LockInternals.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/lock/PersistentAutoIncrement.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransContext.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/lock/TestPersistentAutoIncrement.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransContextManager.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransServiceImpl.java
Also fix the incomplete watermark implementation.
Closes Issue #729.
> [Issue #729] implement persistent transaction id, timestamp, and watermarks

- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/MachineService.java
- pixels-common/src/main/resources/pixels.properties
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/scaling/ScalingMetricsServer.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/scaling/policy/BasicPolicy.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/scaling/policy/helper/FixedSizeQueue.java
- pixels-daemon/src/test/java/io/pixelsdb/pixels/daemon/scaling/policy/helper/TestFixedSizeQueue.java
- pixels-turbo/pixels-scaling-general/src/main/java/io/pixelsdb/pixels/scaling/general/GeneralMetricsCollector.java
- pixels-turbo/pixels-scaling-general/src/main/java/io/pixelsdb/pixels/scaling/general/GeneralMetricsCollectorProvider.java
- pixels-turbo/pixels-scaling-general/src/main/resources/META-INF/services/io.pixelsdb.pixels.common.turbo.MetricsCollectorProvider
- pixels-turbo/pixels-scaling-general/src/main/resources/io.pixelsdb.pixels.common.turbo.MetricsCollectorProvider 
- pixels-turbo/pixels-scaling-general/src/test/java/TestScalingMetricsServer.java
- pom.xml
> [Issue #751] fix scaling bugs and upgrade basic policy

- pixels-turbo/pixels-worker-lambda/README.md
> [Issue #762] add VPC setup doc for deploying lambda workers in aws-cn

- README.md
- docs/INSTALL.md
> [Issue #777] move trino installation instructions into pixels-trino

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
Issue https://github.com/pixelsdb/pixels/issues/779
The timestamp column is read and filtered only if a valid timestamp is passed and the file contains a timestamp column.
> [Issue #779] fix read exception for intermediate files without timestamps column

- docs/INSTALL.md
> [Issue #781] update pixels-trino links

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DateColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimeColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/VectorColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/ColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/VectorizedRowBatch.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestBooleanColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestDateColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestDecimalColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestDoubleColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestFloatColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestLongColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestLongDecimalColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestStringColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestTimeColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestTimestampColumnReader.java
This problem existed for the Date, Time, and Timestamp columns.
> [Issue #791] fix isNull cleared when nullsPadding is enabled

- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterStreamImpl.java
> [Issue #794] warning if stride is multple of 8

- README.md
- cpp/pixels-cli/main.cpp
Add ICDE'25 demo.
Resolves #813.
> [Issue #813] update publications

- README.md
- pixels-cli/pom.xml
- pixels-common/pom.xml
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/DirectIoLib.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/MemoryMappedFile.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/ConfigFactory.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/JvmUtils.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/MetaDBUtil.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/natives/TestNatives.java
- pixels-daemon/pom.xml
> [Issue #841] make MemoryMappedFile compatible with JDK >= 21

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
> [Issue #881] fix PixelsRecordReaderImpl bug

- pixels-retina/src/main/java/io/pixelsdb/pixels/retina/RetinaService.java
- pixels-turbo/pixels-worker-spike/pom.xml
- pom.xml
> [Issue #895] use the spike-java sdk from maven central

- pixels-common/src/main/java/io/pixelsdb/pixels/common/index/IndexService.java
> [Issue #900] Implementation of unique insert interface of MainIndex

- pixels-common/src/main/java/io/pixelsdb/pixels/common/index/IndexService.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/index/MainIndex.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/index/MainIndexImpl.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/index/SinglePointIndex.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/lock/PersistentAutoIncrement.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/index/IndexServiceImpl.java
- pixels-index/pixels-index-rocksdb/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksDBIndex.java
- pixels-index/pixels-index-rockset/src/main/java/io/pixelsdb/pixels/index/rocksdb/RocksetIndex.java
- proto/index.proto
…int put/delete/get and allocateRowIdBatch
> [Issue #916] Redesign the main index implementation to support secondaryIndex and allocateRowIdBatch

- pixels-common/src/main/java/io/pixelsdb/pixels/common/sink/SinkProvider.java
- pixels-common/src/main/resources/pixels.properties
> [Issue #949] check and fix code problems after rebasing master

- pixels-common/src/main/java/io/pixelsdb/pixels/common/retina/RetinaService.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/retina/RetinaServerImpl.java
- proto/retina.proto
> [Issue #986] bidirectional streaming rpc for update records

- proto/sink.proto
> [Issue #964] Remove unused dependency in sink.proto

- pixels-common/pom.xml
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpServer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpServerHandler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpServerInitializer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpServerUtil.java
- pixels-core/pom.xml
- pixels-storage/pixels-storage-http-stream/src/main/java/io/pixelsdb/pixels/storage/http/PhysicalHttpStreamReader.java
- pixels-storage/pixels-storage-http-stream/src/main/java/io/pixelsdb/pixels/storage/http/io/HttpContent.java
- pixels-storage/pixels-storage-http-stream/src/main/java/io/pixelsdb/pixels/storage/http/io/HttpContentQueue.java
- pixels-storage/pixels-storage-http-stream/src/main/java/io/pixelsdb/pixels/storage/http/io/HttpInputStream.java
- pixels-storage/pixels-storage-http-stream/src/main/java/io/pixelsdb/pixels/storage/http/io/HttpOutputStream.java
- pixels-storage/pixels-storage-http-stream/src/test/java/io/pixelsdb/pixels/storage/http/TestHttpStream.java
The writer (client side) sends data contents in an asynchronous manner, and adds an acceding part-id to each content. The reader (server side) receives the data contents and reorders them by the part-id, ensuring the reader sees the data in the same order as the writer.
> [Issue #1024] implement asynchronous data transfer in http streaming storage

- pixels-storage/pixels-storage-http/pom.xml
> [Issue #1033] fix dependencies of storage-http

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/PhysicalWriterUtil.java
> [Issue #1035] fix writer option is null in physical writer util.

- pixels-common/src/main/resources/pixels.properties
- pixels-server/README.md
- pixels-server/pom.xml
- pixels-server/src/main/resources/application.properties
> [Issue #1097] adjust ports for pixels services
