- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/ColumnletId.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/MemoryMappedFile.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-tools/src/main/java/io/pixelsdb/pixels/test/MemMappedFilePerf.java
Implement getDirectByteBuffer in MemoeryMappedFile, build direct byte buffer for columnlets in PixelsRecordReaderImpl, deal with direct byte buffer in column readers.
> [Issue #52]: implement direct shared memory read.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BitUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/ByteBufferInputStream.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/DynamicIntArray.java
Memory copy in double/float/timestamp/string column readers is reduced.
Currently, memory copy only exists for copying dictionary in string column reader. Such memory copy is necessary to improve CPU performance.
> [Issue #55]: reduce memory copy in column readers.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/DynamicIntArray.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestDynamicIntArray.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
Fix bug in DynamicIntArray.toArray() and redundant memory copy for HeapByteBuffer in StringColumnReader.
> [HOTFIX]: bug in DynamicIntArray.toArray() and redundant memory copy.

- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
Add a threshold for gc. If the leave free memory ratio is lower than the given threshold, explicit gc will be issued when closing the PixelsReaderImpl.
> Issue #58: add gc threshold to optimize gc for small queries.

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheManager.java
1. the first 16 bytes in cache file was overwritten when updating cache;
2. wrong current offset is used in PixelsCacheWriter when updating cache.
> Hotfix: fix bugs in CacheWriter initialization and cache update.

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheReader.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/Decoder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/Encoder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/RunLenByteDecoder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/RunLenIntDecoder.java
1. eliminate the memory allocation for edge of nodes;
2. combine the memory read of edge and children into one.
> [Issue #72]: optimize memory allocation and access in PixelsCacheReader.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsPredicate.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/TupleDomainPixelsPredicate.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/TestPixelsPredicate.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestPixelsReaderOption.java
- pixels-hive/src/main/java/io/pixelsdb/pixels/hive/mapred/PixelsInputFormat.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsPageSource.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsSplitManager.java
1. fix predicate processing in `PixelsRecordReaderImpl` and `TupleDomainPixelsPredicate`.
2. correctly support 'is null' and constant predicates.
3. for '=null', the query would still be endless, but this is not due to predicate processing.
> [Issue #103]: fix and enhance predicate processing.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/predicate/PixelsPredicate.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/predicate/TupleDomainPixelsPredicate.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsReaderOption.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/VectorizedRowBatch.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/TestPixelsPredicate.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsPageSource.java
Fix the endless execution of `select count(*) from t` and queries with predicate '=null' (although such predicate is meaningless).
Query with '=null' predicate will return 0 rows in Presto, while the number of scanned rows is the same as result of `select count(*) from t`, which is the total number of rows in `t`.
`select count(*) from t` will only touch the file footers.
> [Issue #105]: fix endless execution for `select count(*)`.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/PixelsCompactor.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/CharColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/VarcharColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/CharColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/ColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/VarcharColumnWriter.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Config.java
1. Varchar and char are implemented based on string type. They only truncate oversized values but not pad zeros/spaces.
2. Data type related methods in PixelsWriterImpl are moved to TypeDescription and ColumnWriter.
> [Issue #100]: refine type management and add varchar/char support.

- pixels-common/pom.xml
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Scheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/impl/PhysicalS3Reader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/impl/S3.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/impl/scheduler/NoopScheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/impl/scheduler/SortMergeScheduler.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/TestS3.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/StringColumnWriter.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestDynamicIntArray.java
- pixels-daemon/pom.xml
- pixels-load/pom.xml
- pixels-presto/pom.xml
- pom.xml
refine read path, replace AtomicReferenceArray with array to refine gc, reduce memory copy for readFully in S3 reader, try AwsCrtAsyncHttpClient.
add clear to RequestBatch.
refine starts array in StringColumnReader.
> [Issue #124]: refine read path.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/BinaryColumnVector.java
The problem is not completely fixed, encoded column vector is needed.
> [Issue #140]: temporary fix for currupt row batch.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/RateLimitedScheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/SortMergeScheduler.java
Previously, the permit to acquire from the mbps rate limiter may be zero, which is invalid.
> [Issue #142]: fix mbps rate-limit.

- README.md
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/LocalFS.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/compactor/CompactLayout.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestFileMetadata.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
Support other storages than HDFS, support compacting tail file.
Some bugs in compact are also fixed.
> [Issue #160]: compact from and to arbitrary storage, including tail files.

- README.md
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/domain/Column.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsTypeManager.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/impl/PixelsMetadataProxy.java
Modify `PixelsTypeManager` in pixels-presto to fix this issue.
> [Issue #163]: fix bounded varchar/char type support.

- README.md
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Storage.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsConnector.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsMetadata.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsModule.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsTableProperties.java
- scripts/sql/tpch_schema.sql
Add table properties to pixels-presto, so that we can use the table property to specify the storage scheme when creating tables.
> [Issue #164]: define storage scheme in CREATE statement.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalS3Reader.java
- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BitUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimestampColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimestampColumnWriter.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestPixelsReaderBasic.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestPixelsReaderOption.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsConnector.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsModule.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsPageSource.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsRecordCursor.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsRecordSet.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsRecordSetProvider.java
1. Add the PixelsRecordSet and PixelsRecordCusor, which can be enabled/disabled by configuration properties, to pixels-presto.
2. Update PixelsRecordReaderImpl.readBatch, let users specify whether they want to reuse the returned result row batch.
Issue #172 is not completely resolved. Record cursor is much slower than the page source for wide tables (they have similar performance on TPC-H). We also tried to implement a context (buffer) of result row batches to automatically allocate, free, and reuse the result row batches. However, it reduces the query performance a lot. This issue can be solved by implementing the read path in C++ in the future.
> [Issue #172]: implement record cursor and enhance record reader.

- README.md
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Scheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/NoopScheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/RateLimitedScheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/SortMergeScheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/QueryTransInfo.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
We have also tried gradually increasing the max merge size per query, but it has a 5-10% performance overhead.
> [Issue #175]: enhance transaction info of queries and pass query id into I/O schedulers.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/dao/impl/EtcdSchemaDao.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsMetadata.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/impl/PixelsMetadataProxy.java
- proto/metadata.proto
Tables in information_schema are system tables. However, Presto still calls the getTables method of the customer ConnectorMetadata class.
> [Issue #179]: fix show tables in information_schema.

- pixels-common/src/main/resources/pixels.properties
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
Use `metrics.server.enabled` to enable or disable the metrics server.
> [Issue #178]: enable metrics server by configuration parameter.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/metadata/MetadataServiceImpl.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/PixelsMetadata.java
select * from information_schema.columns may pass information schema table names into PixelsMetadata.listTableColumns(), so we should check the existence of the table in this method.
> [Issue #183]: fix show columns from information_schema.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Scheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/RateLimitedScheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/SortMergeScheduler.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/QueryTransInfo.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransContext.java
- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
We push down the query id into requests, and check if the query is terminated when retrying the request.
> [Issue #139]: stop retrying the request from terminated queries.

- README.md
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
Support multi-thread compaction and update the docs. 
`cache.read.direct` is removed from the Pixels read path.
> [Issue #192]: support multi-thread compaction.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StatsRecorder.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestPixelsReaderBasic.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/multi/Main.java
- pixels-load/src/test/java/io/pixelsdb/pixels/load/TestPixelsCore.java
- pixels-presto/src/main/java/io/pixelsdb/pixels/presto/impl/PixelsTupleDomainPredicate.java
Previously, the max length of binary/varbinary/char/varchar, and the precision and scale of decimal, are not persisted correctly in the schema of the file footer.
> [Issue #207]: fix the data type metadata in the file footer.

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/AbsoluteBalancer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/Balancer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/ReplicaBalancer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Location.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Storage.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/HDFS.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/LocalFS.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/S3.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
For storage systems such as S3, which does not provide physical data locations, we do not generate mock file locations using etcd. This optimization helps improve the scalability of Pixels. It is important for scanning data using cloud functions as there might be a large number of CF instances scanning data in parallel.
> [Issue #222]: disable mock file locations for storage systems that do not provide data locality.

- README.md
- install.sh
- pixels-common/src/main/resources/pixels.properties
- scripts/sbin/pin-cache.sh
- scripts/sbin/reset-cache.sh
- scripts/sbin/start-pixels.sh
- scripts/sbin/stop-pixels.sh
- scripts/sbin/unpin-cache.sh
close #238 
Part of the installation process is highly mechanized, so we can add a script, which may be more user-friendly.
It will look like this: 
---
Also let `sbin` scripts don't override `PIXELS_HOME` and report missing argument instead.
> [Issue #238]: Add a script to install pixels

- pixels-core/src/main/java/io/pixelsdb/pixels/core/predicate/ColumnFilter.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/predicate/TestPredicate.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
Previously, the discrete value filter on string-based columns may lead to a timeout, as the values in the column vector were not converted to string correctly.
> [Issue #170]: fix discrete filter on string-based columns.

- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/Joiner.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/NullTuple.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/Tuple.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/BroadcastJoinInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/ScanInput.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/predicate/TestBroadcastJoinInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/predicate/TestPartitionInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/predicate/TestScanFile.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/WorkerCommon.java
Implementation broadcast join base-on lambda, and fix the following bugs:
1. key column id can only be ascending;
2. NullTuple does not support includeKey=false;
3. column vector type cast error in Tuple.equals().
> [Issue #170]: implement broadcast join.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
> [Issue #265]: fix reading row group number.

- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/predicate/ColumnFilter.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestBroadcastJoinInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestPartitionInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestPartitionedJoinInvoker.java
Build discrete value hash sets only once in the constructor of the column filter.
> [Issue #271]: improve discrete column filter.

- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/LambdaJoinExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinAlgorithm.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/BroadcastChainJoinInvoker.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/SingleStageJoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/BroadcastChainJoinInput.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestBroadcastChainJoinInvoker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
Disable left outer join and full outer join if the join algorithm is broadcast join.
Rename chain-join as broadcast chain-join, and prepare for partitioned chain-join.
Add post chain join information into broadcast chain-join input.
> [Issue #170]: disable left full outer broadcast join.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/AbstractS3.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/BinaryColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/VarcharColumnWriter.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/LambdaJoinExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/Joiner.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/JoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/PartitionedChainJoinInvoker.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/PartitionedJoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/SingleStageJoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/domain/PartitionInfo.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/BroadcastChainJoinInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/PartitionedChainJoinInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/predicate/ColumnFilter.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestBroadcastChainJoinInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestPartitionInvoker.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/join/TestPartitioner.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
1. Implement multi-pipeline joins so that we can support TPCH q5, q8, and q10.
2. Fix column filter upper bound bug.
3. Fix post-partition number and post-partition key column ids for post partitioning.
4. Fix row group range in the reader option for partitioned join.
5. Fix column writer resetting for partitioned file writing.
6. Start parsing partitioned chain joins, not finished.
> [Issue #258]: support multi-pipeline join and fix bugs.

- pixels-common/src/main/resources/pixels.properties
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/LambdaJoinExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinAdvisor.java
Make sure the split size of the table scan in the joins is not larger than the cap calculated from the data statistics.
This is good for the joins that scan a lot of columns.
> [Issue #258]: implement split size capping.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/DateStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StringStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/TimeStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/TimestampStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/Decimal.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/LongDecimal.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DateColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DecimalColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/LongDecimalColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimeColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimestampColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/ColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/StringColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimestampColumnWriter.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/predicate/ColumnFilter.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/Main.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/ORCConsumer.java
- pixels-load/src/main/java/io/pixelsdb/pixels/load/PixelsConsumer.java
Fix these bugs for the 105-column workload evaluation.
Timestamp now supports 0-6 precisions.
> [Issue #297]: fix timestamp type, stat recorders, null value filtering, and pixels-load.

- pom.xml
Added dependencies for simpleclient_servlet and simpleclient_hotspot.
Upgraded Prometheus version from 0.2.0 to 0.16.0
> [Issue #258]: upgrade Prometheus dependencies.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/BinaryStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/BooleanStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/DateStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/DoubleStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/Integer128StatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/IntegerStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/RangeStats.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StringStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/TimeStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/TimestampStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimestampColumnVector.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
Fix the two bugs:
1. The column statistics were not collected into and read from the files when there are null values.
2. The split size capping is not skipped when the input path is empty.
> [Issue #170]: fix column stats recorders and split size capping.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/VectorizedRowBatch.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/ScanInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/scan/Scanner.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/ScanWorker.java
After reading the needed columns and performing filtering, we further project the columns and drop the columns that are not needed by the upper layer operators.
> [Issue #170]: support scan projection in scan worker.

- pixels-load/src/main/java/io/pixelsdb/pixels/load/Main.java
Previously, the concurrency is limited by the number of copies. Now, we use one thread to copy each file.
> [Issue #170]: improve multi-thread copying.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/CostBasedSplitsIndex.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/IndexFactory.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/InvertedSplitsIndex.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/SplitsIndex.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataCache.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/SchemaTableName.java
- pixels-common/src/main/resources/pixels.properties
- pixels-common/src/test/java/io/pixelsdb/pixels/common/layout/TestCostBasedSplitsIndex.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinAdvisor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/utils/Tuple.java
- pom.xml
The split size capping is removed as it is not needed.
> [Issue #170] add metadata cache and cost-based splits index.

- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/input/JoinInput.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/predicate/TableScanFilter.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/BroadcastJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedChainJoinWorker.java
- pixels-lambda/src/main/java/io/pixelsdb/pixels/lambda/PartitionedJoinWorker.java
In this way, we can reduce the number of intermediate files.
However, this sometimes leads to very large outputs and file writing overhead. We need to further optimize the write performance and the external parallelism.
> [Issue #170]: merge outputs in lambda worker.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataCache.java
- pixels-common/src/main/resources/pixels.properties
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinAdvisor.java
Even though the input size of the table is small, if the table's row count is too large, it should not be broadcast.
Such a table would lead to OOM when building the hash table.
> [Issue #170]: add row count broadcast threshold.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/scheduler/SortMergeScheduler.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/AggregationOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/JoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/Operator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/PartitionedJoinOperator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/lambda/SingleStageJoinOperator.java
Make the execution pipeline of the query operators fully parallelized. Previously, each operator blocks and waits for the completion of its previous stages.
> [Issue #170]: improve execution pipeline.

- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/JoinAdvisor.java
Refine the cost model for calculating the number of partitions in a partitioned join.
> [Issue #170]: improve get num partitions.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/S3OutputStream.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/S3.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/TestS3.java
Asynchronous multi-part upload is not efficient. Thus we use multi-thread multi-part upload.
> [Issue #214]: implement multi-thread S3 output stream.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/BinaryColumnVector.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/aggregation/AggrTuple.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/aggregation/Aggregator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/utils/Tuple.java
Previously, null values are considered non-equal in aggregations. This is incorrect and may lead to very bad performance if there are many null values on the group by key columns.
> [Issue #170]: fix null value processing in aggregation.

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/MemoryMappedFile.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/JvmUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BitUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/HashTableDictionary.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/BinaryColumnVector.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/PixelsExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/StarlingExecutor.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/aggregation/Aggregator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/Joiner.java
- pixels-executor/src/test/java/io/pixelsdb/pixels/executor/TestPixelsExecutor.java
- pixels-lambda/pom.xml
1. improve string comparison in BinaryColumnVector and Dictionary.
2. improve concurrency of Joiner and Aggregator.
3. fix meta service error when creating Pixels/Starling executor.
4. use multiple hash maps in Aggregator to improve the scalability of the hash table.
> [Issue #170]: improve string comparison and aggregation.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/Dictionary.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/BinaryColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DoubleColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/LongDecimalColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/VectorizedRowBatch.java
Previously, the buffer inside BinaryColumnVector was referenced inside HashTableDictionary, but it is overwritten by the next row batch write. This is incorrect. We ensure the buffer is recreated when the row batch is reset for the next row batch write.
> [Issue #367]: fix BinaryColumnVector for dictionary encoding.

- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/RunLenIntEncoder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsReaderOption.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/BinaryColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DictionaryColumnVector.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestPixelsReaderBasic.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/predicate/ColumnFilter.java
Dictionary-encoded column vector avoids decoding the dictionary-encoded column chunks when reading data.
This helps reduce memory allocation and garbage collection. However, Trino currently does not support query execution on encoded data.
> [Issue #369]: implement dictionary-encoded column vector.

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/MemoryMappedFile.java
- pixels-common/pom.xml
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/PhysicalReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/direct/AlignedDirectBuffer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/direct/DirectIoLib.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/direct/DirectRandomAccessFile.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/MockReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalHDFSReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalLocalReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalMinioReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalRedisReader.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/storage/LocalFS.java
- pixels-common/src/main/resources/pixels.properties
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/TestDirect.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/TestGCS.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/TestJNA.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DictionaryColumnVector.java
If local fs is used for table storage, we use Linux system calls to open the files with the o_direct flag and read the files using spread.
Thus, we can by pass the OS page cache.
> [Issue #373]: support direct read on localFS.

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/MemoryMappedFile.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/direct/DirectBuffer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/direct/DirectIoLib.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/direct/DirectRandomAccessFile.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/io/PhysicalLocalReader.java
- pixels-common/src/main/resources/pixels.properties
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/TestDirect.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/direct/TestDirect.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/TestByteBuf.java
We use pread for both direct and non-direct I/O because it is more efficient than JDK's RandomAccessFile.
For non-direct I/O, we allocate the read buffer using malloc, which is more efficient than ByteBuffer.allocateDirect().
> [Issue #379]: support configurable direct/non-direct I/O in LocalFS.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
Fix the bug and rename this method to getCompletedRows.
> [Issue #386]: fix getRowNumber in PixelsRecordReaderImpl.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
Fix the issue that pixels reads replicated content on string column after the first row batch, when the column is not encoded.
> [Issue #414] pixels reads replicated content on string column after the first row batch, when the column is not encoded.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/DateStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/DatetimeUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DateColumnVector.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestBitmap.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestDateTimeUtils.java
In SQL query engines (at least Trino), the Date type does not have a timezone; hence we do not need to add the timezone offset when converting day to milliseconds and vice versa.
With this fix, the query result of the `test_date` table is consistent with the input data in Issue #419.
> [Issue #419] remove timezone offset for date column.

- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/Input.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/WorkerType.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/StringUtil.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/AggregationOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/PartitionedJoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/SingleStageJoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/StarlingAggregationOperator.java
- pixels-turbo/pixels-worker-vhive/src/main/java/io/pixelsdb/pixels/worker/vhive/utils/ServiceImpl.java
The operator name is set in the operators before calling invoke.
For scan-only queries, the scan workers are not invoked by an operator, hence the operator name is not set by default.
> [Issue #468] add operator name to the input of the cloud function workers.

- docs/TPC-H.md
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/AggregationOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/PartitionedJoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/SingleStageJoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/StarlingAggregationOperator.java
- pixels-planner/src/test/java/io/pixelsdb/pixels/planner/TestOutput.java
- pixels-turbo/pixels-worker-vhive/src/main/java/io/pixelsdb/pixels/worker/vhive/utils/ServiceImpl.java
Ensure that the operator name is set for serverless worker inputs when the inputs are added to an operator.
> [Issue #468] improve operator name setting.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DateColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntegerColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/DateColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/IntegerColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/StringColumnWriter.java
1. Pixels Writer: change the big endian to small endian (Date, Int, Long, offset in String).
2. Remove the isLong indicator of integer/long column.
3. This commit is only for generating Pixels data for Pixels C++ reader. Pixels Java reader cannot read data generated by this commit
> Pixels Writer endianness change

- docs/INSTALL.md
In order to compile Pixels, the Maven version should be >= 3.6.
> [docs] Update install.md: Maven version should be above or equal to 3.6.

- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
Unaligned read causes error for SIMD instructions. For example, is the address of a long column vector is 0x0c, it would have unalign read (the address should be the multiple of 8). In the normal instruction it would affect the performance adversely, but we don't know how much performance degrade would happen, but at least here is no correctness issue. However, if we use SIMD, the unalign read is erroneous, so we have to fix it.
We add a parameter in pixels.properties so that we can adjust the alignment value. The default one is 32. It is aligned for avx2(256 bit) SIMD instruction.
Closes #493.
> [Issue #493] Align the location of column byte buffer in pxl file.

- docs/TPC-H.md
- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/Dictionary.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/HashTableDictionary.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/RedBlackTree.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/encoding/StringRedBlackTree.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BitUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/StringColumnWriter.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestDictionary.java
Previously, the orders array was the mapping from the encoded id to the key index in the dictionary. We remove the orders array from the pixels file by enforcing the dictionary to be written in the order of encoded id.
This helps improve writing and reading performance, as it reduces the CPU costs on array encoding/decoding and the IO costs.
> [Issue #498] remove the orders array from dictionary encoding.

- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/StatExecutor.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/CostBasedSplitsIndex.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/InvertedSplitsIndex.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/SplitsIndex.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataCache.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/SchemaTableName.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/SchedulerFactory.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransService.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/layout/TestCostBasedSplitsIndex.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/StarlingPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/PlanOptimizer.java
- pixels-turbo/pixels-worker-vhive/README.md
Ensure the metadata cache is not modified except at the beginning of a query.
Make the metadata cache transactional, so that concurrent queries do not interfere with each other.
> [Issue #485] clean metadata cache and make it transactional.

- cpp/pixels-reader/pixels-core/include/reader/StringColumnReader.h
- cpp/pixels-reader/pixels-core/lib/reader/StringColumnReader.cpp
Remove order in buffer read in Pixels C++
> [Issue #498] remove the orders array from StringColumnReader in C++.

- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/PixelsConsumer.java
Fix the out-of-range issue caused by splitting a row which has the null value
> [Issue #512] Fix the out-of-range issue caused by splitting a row

- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/PixelsConsumer.java
Previously, we can only load multiple tbl files into multiple paths.
> [Issue #517] load single tbl file into multiple paths

- cpp/pixels-reader/pixels-common/lib/physical/natives/DirectUringRandomAccessFile.cpp
Fix the issue that the array `iovecs` in `DirectUringRandomAccessFile` might be freed twice.
Closes #527.
> [Issue #527] Fix the bug that iovecs might free twice

- cpp/PixelsScanFunction.cpp
- cpp/include/PixelsReadLocalState.hpp
- cpp/include/PixelsScanFunction.hpp
- cpp/pixels-reader/pixels-core/include/vector/BinaryColumnVector.h
- cpp/pixels-reader/pixels-core/include/vector/ColumnVector.h
- cpp/pixels-reader/pixels-core/include/vector/DateColumnVector.h
- cpp/pixels-reader/pixels-core/include/vector/DecimalColumnVector.h
- cpp/pixels-reader/pixels-core/include/vector/LongColumnVector.h
- cpp/pixels-reader/pixels-core/include/vector/VectorizedRowBatch.h
- cpp/pixels-reader/pixels-core/lib/reader/PixelsRecordReaderImpl.cpp
- cpp/pixels-reader/pixels-core/lib/vector/BinaryColumnVector.cpp
- cpp/pixels-reader/pixels-core/lib/vector/ColumnVector.cpp
- cpp/pixels-reader/pixels-core/lib/vector/DateColumnVector.cpp
- cpp/pixels-reader/pixels-core/lib/vector/DecimalColumnVector.cpp
- cpp/pixels-reader/pixels-core/lib/vector/LongColumnVector.cpp
- cpp/pixels-reader/pixels-core/lib/vector/VectorizedRowBatch.cpp
PixelsScanFunction is messy. Refactor the code to make it clearer. The fixes are:
1. Add `readIndex` for column vector
2. Move all change state logic to PixelsParallelStateNext
I have already verify its correctness and it doesn't affect the performance.
> [Issue #471] pixels reader c++ code refactor

- pixels-cache/Makefile
- pixels-cache/pom.xml
- pixels-cli/pom.xml
- pixels-common/pom.xml
- pixels-core/pom.xml
- pixels-daemon/pom.xml
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
- pixels-example/pom.xml
- pixels-executor/pom.xml
- pixels-parser/pom.xml
- pixels-planner/pom.xml
- pixels-server/pom.xml
- pixels-storage/pixels-storage-gcs/pom.xml
- pixels-storage/pixels-storage-hdfs/pom.xml
- pixels-storage/pixels-storage-localfs/pom.xml
- pixels-storage/pixels-storage-mock/pom.xml
- pixels-storage/pixels-storage-redis/pom.xml
- pixels-storage/pixels-storage-s3/pom.xml
- pixels-turbo/pixels-invoker-lambda/pom.xml
- pixels-turbo/pixels-invoker-vhive/pom.xml
- pixels-turbo/pixels-scaling-ec2/pom.xml
- pixels-turbo/pixels-worker-common/pom.xml
- pixels-turbo/pixels-worker-lambda/pom.xml
- pixels-turbo/pixels-worker-vhive/pom.xml
- pom.xml
From version 0.1.0-SNAPSHOT to 0.1.0.
> [Issue #535] change project version to 0.1.0

- cpp/PixelsScanFunction.cpp
- cpp/pixels-reader/pixels-core/include/PixelsFilter.h
- cpp/pixels-reader/pixels-core/include/reader/PixelsReaderOption.h
- cpp/pixels-reader/pixels-core/include/reader/PixelsRecordReaderImpl.h
- cpp/pixels-reader/pixels-core/include/vector/ColumnVector.h
- cpp/pixels-reader/pixels-core/include/vector/VectorizedRowBatch.h
- cpp/pixels-reader/pixels-core/lib/PixelsFilter.cpp
- cpp/pixels-reader/pixels-core/lib/reader/PixelsReaderOption.cpp
- cpp/pixels-reader/pixels-core/lib/reader/PixelsRecordReaderImpl.cpp
- cpp/pixels-reader/pixels-core/lib/vector/ColumnVector.cpp
- cpp/pixels-reader/pixels-core/lib/vector/VectorizedRowBatch.cpp
We have verify that the following changes doesn't affect the performance of pixels c++ reader
1. In this pr, we can config the batch size of pixels reader c++. The default value is `pixelStride`
2. Set the length of filter mask as `batchSize` instead of `curRGRowCount`. 
3. Reuse the column vector. We allocate a new column vector only when switching to another pxl file
4. Set a macro to control if we enable SIMD for pixels filter or not
> Make the batch size of pixels c++ reader configurable

- cpp/pixels-reader/pixels-core/lib/PixelsReaderImpl.cpp
`partitioned` has moved from `footer` to `postScript`, so we need to do the fix in the pixels c++ correspondingly.
> Fix compilation error: move partitioned from footer to postScript

- cpp/PixelsScanFunction.cpp
- cpp/pixels-reader/pixels-core/CMakeLists.txt
- cpp/pixels-reader/pixels-core/include/PixelsBitMask.h
- cpp/pixels-reader/pixels-core/include/PixelsFilter.h
- cpp/pixels-reader/pixels-core/include/reader/ColumnReader.h
- cpp/pixels-reader/pixels-core/include/reader/DateColumnReader.h
- cpp/pixels-reader/pixels-core/include/reader/DecimalColumnReader.h
- cpp/pixels-reader/pixels-core/include/reader/IntegerColumnReader.h
- cpp/pixels-reader/pixels-core/include/reader/PixelsRecordReaderImpl.h
- cpp/pixels-reader/pixels-core/include/reader/StringColumnReader.h
- cpp/pixels-reader/pixels-core/lib/PixelsBitMask.cpp
- cpp/pixels-reader/pixels-core/lib/PixelsFilter.cpp
- cpp/pixels-reader/pixels-core/lib/reader/DateColumnReader.cpp
- cpp/pixels-reader/pixels-core/lib/reader/DecimalColumnReader.cpp
- cpp/pixels-reader/pixels-core/lib/reader/IntegerColumnReader.cpp
- cpp/pixels-reader/pixels-core/lib/reader/PixelsRecordReaderImpl.cpp
- cpp/pixels-reader/pixels-core/lib/reader/StringColumnReader.cpp
- cpp/pixels-reader/tests/unit_tests.cpp
We rename `pixelsFilterMask` to `PixelsBitMask`. The reason is that both filter mask and null mask use this class, so we rename it to a more general name.
> [Issue #542] rename pixelsFilterMask to PixelsBitMask

- cpp/README.md
- cpp/pixels-reader/pixels-core/lib/reader/StringColumnReader.cpp
- pixels-common/src/main/resources/pixels.properties
- pixels-core/pom.xml
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/DynamicIntArray.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/EncodingUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/StringColumnWriter.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/TestByteBuf.java
The starts array is not encoded by runlength encoding, and it is padded for null values (we will make this configurable in the next step).
Some variable members in StringColumnReader are renamed:
originsOffset -> dictContentOffset,
startsOffset -> dictStartsOffset,
originBuf -> dictContentBuf,
starts -> dictStarts.
@yuly16 please help update the c++ StringColumnReader accordingly.
> [Issue #539] replace lengths with starts for non-encoded string columns.

- pixels-cli/pom.xml
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/DirectIoLib.java
- pixels-daemon/pom.xml
- pixels-turbo/pixels-invoker-vhive/pom.xml
- pixels-turbo/pixels-worker-common/pom.xml
- pixels-turbo/pixels-worker-lambda/pom.xml
- pixels-turbo/pixels-worker-vhive/pom.xml
- pom.xml
Add log4j-slf4j-impl as the default binding of slf4j.
Add a unified dependency definition for slf4j-api and exclude slf4j-api dependency in other libs including jetcd, jedis, and hadoop. But we do not add this dependency to the modules by default. It can be added as needed in the future.
> [Issue #549] fix dependencies for slf4j

- pixels-cli/pom.xml
- pixels-daemon/pom.xml
- pixels-example/pom.xml
- pixels-turbo/pixels-worker-lambda/pom.xml
- pixels-turbo/pixels-worker-vhive/pom.xml
- pom.xml
Only add the binding when there are no other bindings. Otherwise, there will be conflict bindings problems.
> [Issue #549] resolve conflict bindings between log4j and slf4j

- pixels-amphi/pixels-amphi/src/main/java/io/pixelsdb/pixels/amphi/downloader/PeerDownloader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/StatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/TimeStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/TimestampStatsRecorder.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/DatetimeUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/Decimal.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/LongDecimal.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DateColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/DecimalColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/LongDecimalColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimeColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/TimestampColumnVector.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/ColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/IntegerColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimeColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/TimestampColumnWriter.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestDateTimeUtils.java
1. support precision for time type. This is optional by early Presto but required by Trino.
2. fix stats recorder for time.
3. fix reading non-encoded timestamp columns. The bug was caused by the wrong precision when casting formats.
4. revise parsing string to time and timestamp values.
5. fix the timezone offset problem for timestamp.
> [Issue #556] fix time type and timestamp type

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BooleanColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DateColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntegerColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimeColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BitUtils.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BaseColumnWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BooleanColumnWriter.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/encoding/TestEncoding.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/utils/TestBitUtils.java
In bit compact, big endian means the first element in the input array is compacted as the highest bit of the first byte in the result, and vice versa.
In bit de-compact, big endian means the highest bit of the first byte in the input buffer is de-compacted as the first element in the result, and vice versa.
> [Issue #548] support endianness in bit compact and decompact

- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/writer/BaseColumnWriter.java
- proto/pixels.proto
Add the following property in pixels.properties to control the alignment of the isNull bitmap:
```properties
isnull.bitmap.alignment=8
```
> [Issue #548] support alignment for isNull bitmap

- pixels-cache/README.md
- pixels-cache/pom.xml
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/ColumnChunkId.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheReader.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsPartitionCacheWriter.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsPhysicalReader.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsRadix.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/BenchmarkCacheReader.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPartitionCacheWriter.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
- pixels-daemon/src/main/resources/layout_compact.json
- pixels-daemon/src/main/resources/layout_splits.json
1. Columnlet was used to reference the column chunk in a row group. However, these two terms are confusing in the code and comments. As column chunk is widely used in other literature, we rename all occurrences of columnlet to column chunk.
2. grpc is needed by the unit tests in pixels-cache, we add it back to the pom.
> [Issue #572] rename columnlet to column chunk and fix dependency and comments

- pixels-common/src/main/java/io/pixelsdb/pixels/common/task/Task.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/task/TaskQueue.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/task/TestQueue.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/PlanCoordinator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/PlanCoordinatorFactory.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/StageCoordinator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/StageDependency.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/TaskInfo.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/WorkerCoordinateService.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/WorkerCoordinateServiceImpl.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/AggregationOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/JoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/Operator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/OperatorExecutor.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/PartitionedJoinBatchOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/PartitionedJoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/SingleStageJoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/StarlingAggregationOperator.java
- proto/turbo.proto
Users can initialize the plan coordinator of a query plan by invoking initPlanCoordinator on the root operator of the plan.
TaskId is changed from a string to an integer starting from 0 per stage.
> [Issue #491] implement plan coordinator initialization

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
Under current code, the string column reader does not function correctly, returning wrongly repeated values for string queries.
Debugging found that the problem comes from a wrong variable name in StringColumnReader. Fix as in commit.
> [Issue #579] Fix variable name in StringColumnReader

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/StorageFactory.java
- pixels-example/src/main/java/io/pixelsdb/pixels/example/core/TestPixelsReader.java
- pixels-example/src/main/java/io/pixelsdb/pixels/example/core/TestPixelsWriter.java
This PR makes a simple writer reader test work for s3. Fixed some issues of the test and updated the test to write to and read from a test file on S3 instead of local file system, since pixels is primarily designed to be used as a cloud based system.
> [pixels-example] make simple writer reader test work for s3

- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/Main.java
- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/executor/QueryExecutor.java
This makes query throughput experiments easier.
> [Issue #595] support rate-limited query execution in pixels-cli

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BooleanColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DateColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntegerColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimeColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/VectorColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/BitUtils.java
When reading from multiple column-chunks, column readers did not ensure alignment when decompacting isNull array.
This may lead to skipping some bits in the middle of the isNull bytes in a column chunk and finally read out of the bound of the isNull bytes of a column chunk.
> [Issue #615] fix alignment for isNull decompaction

- pixels-storage/pixels-storage-s3/src/main/java/io/pixelsdb/pixels/storage/s3/AbstractS3.java
Previously, we filtered out the object with exactly the same key of the path. This is incorrect. It filters out the object if the user intends to list an object, or it does not filter out the folder object if the user does not append a "/" to the path.
> [Issue #618] automatically filter out empty folder object in the listStatus method of S3 storage

- pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
- pixels-example/src/main/java/io/pixelsdb/pixels/example/core/ITTestReadVectorColumnFromS3.java
- pixels-example/src/main/java/io/pixelsdb/pixels/example/core/ITTestWriteVectorColumnToS3.java
This PR implements the necessary support in TypeDescription for parsing different schema string as the pixels vector type so that we can use the trino `array(double)` type in trino to query pixels `vector(d)` type, where d is the optional dimension of the vector column.
The main tricky issue was trino `array(double)` doesn't support a fixed dimension where as pixels `vector(d)` type uses a fixed dimension to simplify and speed up calculations. This issue is resolved by letting `TypeDescription` be able to parse different schema strings from trino (`array(double)`) or pixels files (`vector(d)`). This way we can simply use `PixelsWriter` to write pxl files to S3 and then read them from trino using `array(double)`, but the actual type read from s3 will be `vector(d)`, and will be turned into …
> [Issue #580] make pixels vector type support trino array type

- pixels-common/src/main/java/io/pixelsdb/pixels/common/layout/IndexFactory.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
Otherwise, if a table with the same schemaTableName but a different schema is created later, the outdated splits and projections cache may cause problems.
> [Issue #630] drop cached splits and projections indexes when drop table or schema

- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/response/GetQueryResultResponse.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransContextCache.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransService.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransServiceImpl.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
- pixels-turbo/README.md
- proto/transaction.proto
Add rpc protocol to set query costs as transaction properties.
Get the spent and billed cents from the transaction service.
Return the query costs and the query pending time in the get query result response.
> [Issue #506] get query costs from transaction service

- docs/INSTALL.md
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/ExecutionHint.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/PriceModel.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransService.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
- pixels-common/src/main/resources/pixels.properties
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransServiceImpl.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/StarlingPlanner.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
- pixels-server/src/test/java/io/pixelsdb/pixels/server/TestQueryAPI.java
- pixels-turbo/README.md
- proto/transaction.proto
Allow pixels-trino to set scan size in the transaction properties and use it to calculate the billed cents.
> [Issue #506] support billed cents in pixels-server

- docs/INSTALL.md
- pixels-cli/src/test/java/io/pixelsdb/pixels/cli/TestExecuteQuery.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/state/StateManager.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/state/StateWatcher.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransService.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/Output.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/SimpleOutput.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/state/TestStateManager.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/VectorColumnStats.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/stats/VectorStatsRecorder.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransServiceImpl.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/StarlingPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/AggregationBatchOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/AggregationOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/AggregationStreamOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/OperatorExecutor.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/PartitionedJoinBatchOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/PartitionedJoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/PartitionedJoinStreamOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/SingleStageJoinBatchOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/SingleStageJoinOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/SingleStageJoinStreamOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/StarlingAggregationOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/domain/MultiOutputInfo.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/domain/OutputInfo.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/ScanInput.java
- pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BaseScanWorker.java
- proto/transaction.proto
1. Revise the operators in pixels-planer to support getting output from the return value of the execute() method.
2. Add methods for the VM workers to check the status of the root operator executed in CF workers.
3. Add methods for the VM cluster to clean the states and intermediate results.
4. Fix a bug in PartitionedJoinOperator.execute().
5. Add protocol for the VM cluster to report scan bytes and cost cents more efficiently.
> [Issue #506] support cost cents collection

- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/Output.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/turbo/SimpleOutput.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/PixelsPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/StarlingPlanner.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/PlanCoordinator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/PlanCoordinatorFactory.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/StageCoordinator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/StageDependency.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/coordinate/TaskBatch.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/AggregationBatchOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/AggregationOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/Operator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/ScanBatchOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/ScanOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/ScanStreamOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/SingleStageJoinBatchOperator.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/input/ScanInput.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/output/NonPartitionOutput.java
- pixels-planner/src/main/java/io/pixelsdb/pixels/planner/plan/physical/output/PartitionOutput.java
- pixels-turbo/pixels-invoker-lambda/src/test/java/io/pixelsdb/pixels/invoker/lambda/TestPartitionLambdaInvoker.java
- pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BasePartitionWorker.java
1. add scan operator for serverless workers.
2. pixels and starling planner accepts base table and generate scan operator for table scan.
3. fix output collection in aggregation operators, it doesn't collect child output previously.
4. fix ScanInput.generateOutputPaths(), it only generates outputs end with even numbers previously.
5. move outputs from NonPartitionOutput into Output.
6. add comments for worker coordinators.
> [Issue #643] add scan operator and fix scan input and aggregation operators

- pixels-common/src/main/java/io/pixelsdb/pixels/common/error/ErrorCode.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/rest/response/GetQueryResultResponse.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransService.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/DaemonMain.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/transaction/TransServiceImpl.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/constant/ControllerParameters.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryController.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
- pixels-server/src/test/java/io/pixelsdb/pixels/server/TestQueryAPI.java
- proto/transaction.proto
Clean the result of finished queries periodically instead of immediately after the first getQueryResult request.
Fix 'Query is not finished' for the repeated getQueryResult requests.
Fix dead-lock in popQueryResult of QueryManager.
Clean code.
Closes Issue #649.
> [Issue #649] clean query results periodically and fix bugs in query manager

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/Location.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/TestRandom.java
For locality-insensitive storage, the file locations should have empty hosts. Otherwise, the hosts may be confusing for query engines such as Trino.
> [Issue #653] fix hosts for file locations

- cpp/README.md
- cpp/pixels-common/CMakeLists.txt
Replace PIXELS_HOME with PIXELS_SRC to locate proto file. PIXELS_SRC is the source path of pixels. PIXELS_HOME is the installation path of pixels.
> [Issue #657] add PIXELS_SRC environment variable to compile pixels c++

- cpp/pixels-common/include/utils/ConfigFactory.h
- cpp/pixels-common/lib/utils/ConfigFactory.cpp
pixels-example should read the example.pxl file from PIXELS_SRC instead of PIXELS_HOME
> [Issue #660] pixels-example should read the example.pxl file from PIXELS_SRC

- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
We include the time of collecting rows from ResultSet in the execution time of a query.
> [Issue #695] fixed execution time statistics in pixels-server

- pixels-turbo/pixels-worker-vhive/pom.xml
The jar package created by maven assembly plugin will lack DnsNameResolverProvider in /META-INF/services/io.grpc. So substitue it with maven shade plugin.
Refer to https://github.com/grpc/grpc-java/issues/9829 and https://github.com/grpc/grpc-java/issues/9387
> [Issue #703] fix missing DnsNameResolverProvider in /META-INF/services/io.grpc.

- pixels-core/src/main/java/io/pixelsdb/pixels/core/utils/Integer128.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/aggregation/function/DecimalSum.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/aggregation/function/FunctionFactory.java
Previously, the sum aggregation for decimals only works correctly when the input and output type of DecimalSum are short decimals.
Closes #647.
> [Issue #647] fix sum aggregation with long decimal intermediate results

- pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/TestMetadataService.java
- pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/analyzer/TestPlanAnalysis.java
- pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/coordinator/TestCoordinator.java
- pixels-amphi/src/test/java/io/pixelsdb/pixels/amphi/downloader/TestPeerDownloader.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/CacheLocationDistribution.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/AbsoluteBalancer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/Balancer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/ReplicaBalancer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/MetadataService.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/server/HostAddress.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/transaction/TransService.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/TestBalancer.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/TestMetadataService.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/compactor/TestPixelsCompactor.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
- pixels-parser/src/test/java/io/pixelsdb/pixels/parser/TestPixelsParser.java
- pixels-parser/src/test/java/io/pixelsdb/pixels/parser/TestPixelsSchema.java
- pixels-server/src/main/java/io/pixelsdb/pixels/server/controller/QueryManager.java
No need to shut down all created instances. Avoid double shutting down the default instance.
> [Issue #715] revise trans and metadata services

- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheWorker.java
This issue is not due to the heartbeat service problem. It is caused by the wrong worker node hostnames in the CacheCoordinator.updateCachePlan().
> [Issue #715] fix the worker hostnames in the cache plan

- docs/INSTALL.md
- pixels-cache/README.md
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheConfig.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/BenchmarkCacheIndexReader.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/BenchmarkCacheReader.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPartitionCacheReader.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPartitionCacheWriter.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/balance/AbsoluteBalancer.java
- pixels-common/src/main/resources/pixels.properties
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/heartbeat/HeartbeatConfig.java
- scripts/bin/start-vmtouch.sh
- scripts/bin/stop-vmtouch.sh
1. rename `lease.ttl.seconds` and `enable.absolute.balancer` to `heartbeat.lease.ttl.seconds` and `cache.absolute.balancer.enabled`, respectively.
2. Revise the document for pixels cache, add vmtouch installation, and make it consistent with the code.
3. minor revision of the code and scripts.
> [Issue #724] update configurations and docs for pixels-cache

- pixels-cache/README.md
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheConfig.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsPhysicalReader.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/BenchmarkCacheIndexReader.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/BenchmarkCacheReader.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPartitionCacheReader.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPartitionCacheWriter.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/metadata/SchemaTableName.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
- pixels-common/src/main/resources/pixels.properties
- pixels-core/src/test/java/io/pixelsdb/pixels/core/writer/TestPixelsWriter.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheCoordinator.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheWorker.java
- scripts/sbin/reset-cache.sh
1. Now, the cache schema and table names are specified in the layout_version and cache_version values.
2. Close PixelsPhysicalReader in PixelsCacheWriter to release the off-heap buffers allocated for localFs.
3. Revise the pixels cache document.
> [Issue #636] remove cache schema and table from config file and fix memory leak in cache writer

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/StreamPath.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpServer.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/HttpServerHandler.java
- pixels-storage/pixels-storage-stream/pom.xml
- pixels-storage/pixels-storage-stream/src/main/java/io/pixelsdb/pixels/storage/stream/PhysicalStreamReader.java
- pixels-storage/pixels-storage-stream/src/main/java/io/pixelsdb/pixels/storage/stream/PhysicalStreamWriter.java
- pixels-storage/pixels-storage-stream/src/main/java/io/pixelsdb/pixels/storage/stream/Stream.java
- pixels-storage/pixels-storage-stream/src/main/java/io/pixelsdb/pixels/storage/stream/StreamProvider.java
- pixels-storage/pixels-storage-stream/src/main/java/io/pixelsdb/pixels/storage/stream/io/StreamInputStream.java
- pixels-storage/pixels-storage-stream/src/main/java/io/pixelsdb/pixels/storage/stream/io/StreamOutputStream.java
- pixels-storage/pixels-storage-stream/src/test/java/io/pixelsdb/pixels/storage/stream/TestStream.java
- pom.xml
> [Issue #707] implement stream storage

- pixels-cli/src/main/java/io/pixelsdb/pixels/cli/load/PixelsConsumer.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/TypeDescription.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ByteColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/ColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsReaderOption.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderStreamImpl.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/IntColumnVector.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/TestColumnVector.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestIntegerColumnReader.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/aggregation/Aggregator.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/Joiner.java
- pixels-executor/src/main/java/io/pixelsdb/pixels/executor/join/Partitioner.java
This is for the compatability of Trino 466.
Closes #784.
> [Issue #784] support read int columns as int column vectors

- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/BooleanColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DateColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/DoubleColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/FloatColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/IntColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/LongDecimalColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/StringColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimeColumnReader.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/TimestampColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestBooleanColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestDateColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestDecimalColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestDoubleColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestFloatColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestIntColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestLongColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestLongDecimalColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestStringColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestTimeColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestTimestampColumnReader.java
- pixels-core/src/test/java/io/pixelsdb/pixels/core/reader/TestVectorColumnReader.java
1. add more tests;
2. fix bitmap alignment to the pixel boundary when pixelsStride is not aligned to 8. This affects isNull bitmap reading of all types and the value reading of Boolean;
3. fix the buffer out-of-bound problem in readSelected of Int and Long when nulls padding is disabled, value should be read only when the value at the position is not null;
4. fix readSelected of String, isNull bitmap should be firstly read into the temporary isNull boolean array.
Closes #789.
> [Issue #789] fix aligning bitmap read to pixel boundary; fix readSelected of Int, Long, and String

- pom.xml
The upgrade does not provide obvious performance gain on TPC-H q6 and q8.
Closes #795.
> [Issue #795] upgrade aws sdk to version 2.29.31

- cpp/CMakeLists.txt
- cpp/README.md
- cpp/pixels-cli/CMakeLists.txt
- cpp/pixels-common/CMakeLists.txt
Also update the README and use the official liburing repository.
> [Issue #806] download and build boost automatically in cmake

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/DirectIoLib.java
- pixels-core/src/main/java/io/pixelsdb/pixels/core/PixelsWriterStreamImpl.java
Issue #819
fix constructor for java.nio.DirectByteBuffer and replace NotImplementedException with UnsupportedOperationException
> [Issue #819] fix constructor for java.nio.DirectByteBuffer

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/DirectIoLib.java
- pixels-daemon/pom.xml
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/scaling/policy/AIASPolicy.java
- pom.xml
> [Issue #819] revise jdk version check for reflect constructor

- pom.xml
The problem in Issue #826 can not be reproduced, however, we revise the dependency for aws-crt-client to make it cleaner.
> [Issue #826] revise dependency for aws-crt-client

- pixels-common/src/main/resources/pixels.properties
These worker names were lost during the rebasing process.
Resolves #949.
> [Issue #949] add missing spike worker names into pixels.properties

- pixels-cache/README.md
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/CacheScalingOperation.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsBucketToZoneMap.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsBucketTypeInfo.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheConfig.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheReader.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheUtil.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsCacheWriter.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsHasher.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsLocator.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsMurmurHasher.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsZoneReader.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsZoneUtil.java
- pixels-cache/src/main/java/io/pixelsdb/pixels/cache/PixelsZoneWriter.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPixelsCacheReader.java
- pixels-cache/src/test/java/io/pixelsdb/pixels/cache/TestPixelsCacheWriter.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/MemoryMappedFile.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/utils/Constants.java
- pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/cache/CacheWorker.java
commit 1st: implements a multi-zone non-blocking caching framework
commit 2nd: implements online cache scaling
commit 3rd: handles the deprecation of the cacheBorder parameter
NOTE:  This feature is compatible with the pixels-trino/Trino-405 branch at present.
Cache Online Scaling Feature Usage Notes:
i.   CacheWorker monitors the cache_expand_or_shrink field in ETCD to perform cache expansion or shrink operations. The field values are interpreted as follows:
0: No scaling operation (default state)
1: Trigger cache expansion (scale out)
2: Trigger cache shrink(scale in)
e.g.    etcdctl --endpoints=cds01:2379 put cache_expand_or_shrink 1
ii.   The scaling operation does not aim to change the config file, once the PixelsWorker restarts, the scaling is no longer in effect.
iii.   "shrink" …
> [Issue #957] Implement a multi-zone non-blocking caching framework with online cache scaling capabilities

- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/DirectIoLib.java
- pixels-common/src/main/java/io/pixelsdb/pixels/common/physical/natives/MemoryMappedFile.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/TestJNA.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/natives/TestMemFile.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/natives/TestMemFileConcurrentRW.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/natives/TestMemFileWrite.java
- pixels-common/src/test/java/io/pixelsdb/pixels/common/physical/natives/TestNatives.java
This improves compatibility across different JDK versions and eliminates the 2GB size limitation of the underlying file.
Resolves #960.
> [Issue #960] use mmap/munmap in standary c library for memory mapped file

- pixels-storage/pixels-storage-http/src/main/java/io/pixelsdb/pixels/storage/http/io/HttpInputStream.java
- pixels-storage/pixels-storage-http/src/main/java/io/pixelsdb/pixels/storage/http/io/HttpServer.java
Previously, the hostname was ignored.
Resolves #1038.
> [Issue #1038] support specifiying host name in http stream reader

- pixels-amphi/README.md
- pixels-amphi/pom.xml
- pixels-amphi/src/main/java/io/pixelsdb/pixels/amphi/downloader/DownloadProcess.java
- pixels-cli/pom.xml
- pixels-daemon/pom.xml
- pixels-parser/pom.xml
- pixels-server/pom.xml
- pixels-server/src/main/resources/templates/login.html
- pixels-turbo/pixels-worker-vhive/pom.xml
- pom.xml
This resolves the problems with pixels-server, which is caused by the conflicting log libraries in pixels-amphi and pixels-parser.
We also update the pom of pixels-amphi, making other components such as pixels-server dependent on the origin instead of the uber jar of pixels-amphi
> [Issue #1094] resolve conflicting log libraries

- pixels-amphi/src/main/java/io/pixelsdb/pixels/amphi/coordinator/Coordinator.java
- pixels-server/pom.xml
- pixels-storage/pixels-storage-s3/pom.xml
log4j-slf4j-impl may cause conflicts with other modules, such as pixels-trino, regarding logging.
> [Issue #1094] avoid inheriting log4j-slf4j-impl dependency from storage-s3 to other modules
